import Head from "next/head";
import Image from "next/image";

import Header from "@/components/Header";
import Dashboard from "@/components/Dashboard";
import Calendar from "@/components/Calendar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shar's Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <Dashboard />
        <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          <Calendar />
        </div>
      </main>
    </>
  );
}